# Generated by Django 4.1.3 on 2023-01-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=11, verbose_name='Cédula')),
                ('fechaNacimiento', models.DateTimeField(auto_now_add=True)),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
            ],
        ),
    ]
