# Generated by Django 4.1.3 on 2023-01-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateTimeField(),
        ),
    ]
