# Generated by Django 4.1.3 on 2023-01-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0003_alter_paciente_fechanacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=11, verbose_name='Cédula')),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
        ),
    ]
