# Generated by Django 4.1.3 on 2023-01-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0004_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(max_length=100, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nUsuario',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(max_length=100, null=True, verbose_name='Rol'),
        ),
    ]
