# Generated by Django 4.1.3 on 2023-01-22 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0008_alter_paciente_sexo_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivoConsulta', models.TextField(max_length=200, verbose_name='Motivo Consulta')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMD.paciente')),
            ],
        ),
    ]
