# Generated by Django 4.1.3 on 2023-01-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0009_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('antibioticosAlergia', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('anestesiaAlergia', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('hemorragias', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('sida', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('tuberculosis', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('asma', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('diabetes', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('cardiacas', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('otros', models.TextField(max_length=200, verbose_name='Motivo Consulta')),
            ],
        ),
        migrations.AlterField(
            model_name='historia',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMD.paciente', verbose_name='Codigo del paciente'),
        ),
    ]
