# Generated by Django 4.1.3 on 2023-01-26 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0011_historia_enfermedad_alter_enfermedad_otros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='enfermedad',
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMD.paciente')),
            ],
            options={
                'ordering': ['-date', 'heure'],
            },
        ),
    ]
