# Generated by Django 4.1.3 on 2023-06-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0017_alter_cita_options_alter_historia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='motivoConsulta',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
    ]
