# Generated by Django 4.1.3 on 2023-06-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0019_historia_anestesiaalergia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='atm',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='A.T.M.'),
        ),
        migrations.AddField(
            model_name='historia',
            name='carrillo',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Carrillo'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento10',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento11',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento12',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento8',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento9',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo Consulta'),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento10',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento11',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento12',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento4',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento5',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento6',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento7',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento8',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento9',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='frecuenciaCardiaca',
            field=models.CharField(max_length=10, null=True, verbose_name='Frecuencia Cardiaca'),
        ),
        migrations.AddField(
            model_name='historia',
            name='frecuenciaRespiratoria',
            field=models.CharField(max_length=10, null=True, verbose_name='Frecuencia respiratoria'),
        ),
        migrations.AddField(
            model_name='historia',
            name='ganglios',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Ganglios'),
        ),
        migrations.AddField(
            model_name='historia',
            name='glándulasSalivales',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Glándulas salivales'),
        ),
        migrations.AddField(
            model_name='historia',
            name='labios',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Labios'),
        ),
        migrations.AddField(
            model_name='historia',
            name='lengua',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Lengua'),
        ),
        migrations.AddField(
            model_name='historia',
            name='maxilarSuperior',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Maxilar superior'),
        ),
        migrations.AddField(
            model_name='historia',
            name='mejillas',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Mejillas'),
        ),
        migrations.AddField(
            model_name='historia',
            name='orofaringe',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Orofaringe'),
        ),
        migrations.AddField(
            model_name='historia',
            name='paladar',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Paladar'),
        ),
        migrations.AddField(
            model_name='historia',
            name='piso',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='historia',
            name='presionArterial',
            field=models.CharField(max_length=10, null=True, verbose_name='Presión Arterial'),
        ),
        migrations.AddField(
            model_name='historia',
            name='temperatura',
            field=models.CharField(max_length=10, null=True, verbose_name='Temperatura'),
        ),
    ]
