# Generated by Django 4.1.3 on 2023-06-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0021_rename_glándulassalivales_historia_glandulassalivales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='desTratamiento10',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='desTratamiento11',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='desTratamiento12',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='desTratamiento5',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='desTratamiento6',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='desTratamiento7',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='desTratamiento8',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='desTratamiento9',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='fechaTratamiento10',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='fechaTratamiento11',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='fechaTratamiento12',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='fechaTratamiento5',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='fechaTratamiento6',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='fechaTratamiento7',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='fechaTratamiento8',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='fechaTratamiento9',
        ),
        migrations.AddField(
            model_name='historia',
            name='hipertension',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=11, null=True, verbose_name='Hipertensión'),
        ),
        migrations.AddField(
            model_name='historia',
            name='maxilarInferior',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Maxilar Inferior'),
        ),
    ]
