# Generated by Django 4.1.3 on 2023-06-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0023_remove_historia_anestesiaalergia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='antibioticosAlergia',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True, verbose_name='Alergia antibióticos'),
        ),
    ]
