# Generated by Django 4.1.3 on 2023-06-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0024_alter_historia_antibioticosalergia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='antibioticosAlergia',
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='otros',
            field=models.TextField(blank=True, max_length=200, verbose_name='Otros'),
        ),
    ]
