# Generated by Django 4.1.3 on 2023-06-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0026_historia_antibioticosalergia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='anestesiaAlergia',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=11, null=True, verbose_name='Alergia anestesia'),
        ),
        migrations.AddField(
            model_name='historia',
            name='asma',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=11, null=True, verbose_name='Asma'),
        ),
        migrations.AddField(
            model_name='historia',
            name='atm',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='A.T.M.'),
        ),
        migrations.AddField(
            model_name='historia',
            name='cardiacas',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=11, null=True, verbose_name='Enfermedad cardiacas'),
        ),
        migrations.AddField(
            model_name='historia',
            name='carrillo',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Carrillo'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripcion tratamient 1'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripcion tratamient 2'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripcion tratamient 3'),
        ),
        migrations.AddField(
            model_name='historia',
            name='desTratamiento4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripcion tratamient 4'),
        ),
        migrations.AddField(
            model_name='historia',
            name='diabetes',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=11, null=True, verbose_name='Diabetes'),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='fechaTratamiento4',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='frecuenciaCardiaca',
            field=models.CharField(max_length=10, null=True, verbose_name='Frecuencia Cardiaca'),
        ),
        migrations.AddField(
            model_name='historia',
            name='frecuenciaRespiratoria',
            field=models.CharField(max_length=10, null=True, verbose_name='Frecuencia respiratoria'),
        ),
        migrations.AddField(
            model_name='historia',
            name='ganglios',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Ganglios'),
        ),
        migrations.AddField(
            model_name='historia',
            name='glandulasSalivales',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Glándulas salivales'),
        ),
        migrations.AddField(
            model_name='historia',
            name='hemorragias',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=11, null=True, verbose_name='Hemorrágias'),
        ),
        migrations.AddField(
            model_name='historia',
            name='hipertension',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=11, null=True, verbose_name='Hipertensión'),
        ),
        migrations.AddField(
            model_name='historia',
            name='labios',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Labios'),
        ),
        migrations.AddField(
            model_name='historia',
            name='lengua',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Lengua'),
        ),
        migrations.AddField(
            model_name='historia',
            name='maxilarInferior',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Maxilar Inferior'),
        ),
        migrations.AddField(
            model_name='historia',
            name='maxilarSuperior',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Maxilar superior'),
        ),
        migrations.AddField(
            model_name='historia',
            name='mejillas',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Mejillas'),
        ),
        migrations.AddField(
            model_name='historia',
            name='orofaringe',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Orofaringe'),
        ),
        migrations.AddField(
            model_name='historia',
            name='paladar',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Paladar'),
        ),
        migrations.AddField(
            model_name='historia',
            name='piso',
            field=models.CharField(choices=[('B', 'Bueno'), ('M', 'Malo')], max_length=11, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='historia',
            name='presionArterial',
            field=models.CharField(max_length=10, null=True, verbose_name='Presión Arterial'),
        ),
        migrations.AddField(
            model_name='historia',
            name='sida',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=11, null=True, verbose_name='VIH/SIDA'),
        ),
        migrations.AddField(
            model_name='historia',
            name='temperatura',
            field=models.CharField(max_length=10, null=True, verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='historia',
            name='tuberculosis',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=11, null=True, verbose_name='Tuberculosis'),
        ),
    ]
