# Generated by Django 4.1.3 on 2023-06-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMD', '0027_historia_anestesiaalergia_historia_asma_historia_atm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
